version: '3.8'
services:
  posts-service:
    build: .
    container_name: posts-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: posts-service

      SPRING_CONFIG_IMPORT: optional:consul:/
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_blog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      SPRING_LIQUIBASE_CHANGE_LOG: classpath:liquibase-changelog.xml

      SPRING_WEB_ERROR_INCLUDE_MESSAGE: always
      SPRING_WEB_ERROR_INCLUDE_STACKTRACE: never

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-server:8083/oauth2/jwks

    networks:
      - shared-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: travel_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-net

volumes:
  postgres_data:

networks:
  shared-net:
    external: true